name: build-and-test-macos
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"
jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ macos-12, macos-13 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      # Parallel tests
      - run: go test ./...
